"""
grapx.readwrite.edgelist
~~~~~~~~~~~~~~~~~~~~~~~~~~
Read and write graphs as edge lists (CSV / space-delimited text).
"""

from __future__ import annotations

import contextlib

from grapx.classes.graph import Graph


def read_edgelist(
    path,
    comments: str = "#",
    delimiter: str | None = None,
    create_using=None,
    nodetype=None,
    data=True,
    edgetype=None,
    encoding: str = "utf-8",
) -> Graph:
    """
    Read a graph from an edge list file.

    Each line should contain two node identifiers (and optionally attributes).

    Parameters
    ----------
    path : str or file-like
        Path to the edge list file, or a file-like object.
    comments : str
        Lines beginning with this character are skipped (default ``"#"``).
    delimiter : str or None
        Field separator. ``None`` → any whitespace.
    create_using : callable or None
        Graph constructor. Default: ``Graph`` (undirected).
    nodetype : callable or None
        Convert node strings using this function (e.g. ``int``, ``str``).
    data : bool or list of (name, type) pairs
        If ``True``, parse remaining fields as a dict with keys ``"weight"``,
        ``"attr2"``, etc.  If ``False``, ignore extra fields.
    encoding : str
        File encoding (default ``"utf-8"``).

    Returns
    -------
    Graph or DiGraph
    """
    G = (create_using() if create_using else Graph())

    def _open(p, enc):
        if hasattr(p, "read"):
            return p
        return open(p, encoding=enc)

    fh = _open(path, encoding)
    try:
        for line in fh:
            line = line.strip()
            if not line or line.startswith(comments):
                continue
            parts = line.split(delimiter) if delimiter else line.split()
            if len(parts) < 2:
                continue
            u_str, v_str = parts[0], parts[1]
            u = nodetype(u_str) if nodetype else u_str
            v = nodetype(v_str) if nodetype else v_str

            # Parse edge attributes
            attr: dict = {}
            if data is True and len(parts) > 2:
                try:
                    attr["weight"] = float(parts[2])
                except ValueError:
                    attr["weight"] = parts[2]
                for i, extra in enumerate(parts[3:], 2):
                    attr[f"attr{i}"] = extra
            elif isinstance(data, list):
                for i, (name, cast) in enumerate(data):
                    if i + 2 < len(parts):
                        with contextlib.suppress(ValueError, IndexError):
                            attr[name] = cast(parts[i + 2])

            G.add_edge(u, v, **attr)
    finally:
        if not hasattr(path, "read"):
            fh.close()

    return G


def write_edgelist(
    G: Graph,
    path,
    comments: str = "#",
    delimiter: str = " ",
    data: bool | list = True,
    encoding: str = "utf-8",
) -> None:
    """
    Write *G* as an edge list to *path*.

    Parameters
    ----------
    G : Graph or DiGraph
    path : str or file-like
        Destination file path or file-like object.
    comments : str
        Header comment prefix.
    delimiter : str
        Field separator (default ``" "``).
    data : bool or list of str
        If ``True``, include all edge attributes.  If a list of attribute names,
        include only those attributes.  If ``False``, write only ``u v``.
    encoding : str
        File encoding (default ``"utf-8"``).
    """

    def _open(p, enc):
        if hasattr(p, "write"):
            return p
        return open(p, "w", encoding=enc, newline="")

    fh = _open(path, encoding)
    try:
        fh.write(f"{comments} edge list generated by grapx\n")
        for u, v, attrs in G.edges(data=True):
            row = [str(u), str(v)]
            if data is True:
                if "weight" in attrs:
                    row.append(str(attrs["weight"]))
                extras = {k: v for k, v in attrs.items() if k != "weight"}
                for val in extras.values():
                    row.append(str(val))
            elif isinstance(data, list):
                for name in data:
                    row.append(str(attrs.get(name, "")))
            fh.write(delimiter.join(row) + "\n")
    finally:
        if not hasattr(path, "write"):
            fh.close()


def generate_edgelist(G: Graph, delimiter: str = " ", data: bool = True):
    """
    Yield lines of an edge list for *G* (does not write to disk).
    """
    for u, v, attrs in G.edges(data=True):
        row = [str(u), str(v)]
        if data and "weight" in attrs:
            row.append(str(attrs["weight"]))
        yield delimiter.join(row)


__all__ = [
    "read_edgelist",
    "write_edgelist",
    "generate_edgelist",
]
